### ISSUE TITLE
新規タスクを作成できない件

### ISSUE THREAD

**Issue by keiichirotakahashi** [Tatsuki-Tsujita2/my_front#1]
- form タグの onSubmit で submit イベントを発火させるためには button タグの type 属性を submit にする必要があります！（以下のコンポーネントに`type="submit"` のpropsを追加する必要があります）
https://github.com/Tatsuki-Tsujita2/my_front/blob/0048fdd71331e22fc6406f09860b0f146d193d7d/src/components/TodoList.js#L118
- また、それだけだと submit イベントの発火時にページ遷移してしまうので、handleSubmit 関数に event などの引数を渡してあげて、関数内で `event.preventDefault()` を呼び出してあげた方が良いです！
https://github.com/Tatsuki-Tsujita2/my_front/blob/0048fdd71331e22fc6406f09860b0f146d193d7d/src/components/TodoList.js#L38-L53

**Comment by Tatsuki-Tsujita2** [comment]
コードレビューありがとうございます！
ご指摘通り(e)という引数を渡し、新規タスクを作成できました！
ですがイベント発火時にページ偏移している様に見えるのですが、再度ご確認いただけますでしょうか。

**Comment by keiichirotakahashi** [comment]
コメントしました！
https://github.com/Tatsuki-Tsujita2/my_front/commit/7fc7977b990d6b95a12031461684c88618933ba4#r71529786
